const $ = id => document.getElementById(id);
let state;
function message(text,error=false){$('message').hidden=false;$('message').textContent=text;$('message').className=error?'error':'';}
async function action(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message || String(e),true);}finally{buttons.forEach(b=>b.disabled=false);}}
function renderJobs(jobs){$('jobs').replaceChildren();if(!jobs.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=4;cell.textContent='No receipts yet. Print a test to check your setup.';row.append(cell);$('jobs').append(row);return;}for(const job of jobs){const row=document.createElement('tr');for(const value of [job.id.slice(0,8),new Date(job.createdAt).toLocaleString(),state.preview && job.state==='submitted'?'Preview only':job.state,job.error || (job.spoolId ? `Windows job #${job.spoolId}`:'—')]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}$('jobs').append(row);}}
async function load(fill=true){state=await window.agent.state();$('status').textContent=state.apiError?'API unavailable':state.preview?'Preview mode · no printing':'Agent ready';$('endpoint').textContent=state.endpoint;if(fill){const s=state.settings;$('printer').replaceChildren(new Option('Choose your receipt printer',''));const names=[...new Set([...state.printers,...(s.printer?[s.printer]:[])])];names.forEach(name=>$('printer').add(new Option(name,name)));$('printer').value=s.printer;$('paper').value=s.paper;$('columns').value=s.columns;$('cut').value=s.cut;$('feed').value=s.feedLines;$('auto').checked=s.autoStart;$('origins').value=s.allowedOrigins.join('\n');$('receipt').textContent=state.receipt;}renderJobs(state.jobs);if(state.apiError)message(`Local connection unavailable: ${state.apiError}`,true);}
$('settings').addEventListener('submit',e=>{e.preventDefault();action(async()=>{await window.agent.save({printer:$('printer').value,paper:$('paper').value,columns:Number($('columns').value),cut:$('cut').value,feedLines:Number($('feed').value),autoStart:$('auto').checked,allowedOrigins:$('origins').value.split('\n').map(x=>x.trim()).filter(Boolean)});message('Settings saved. You can now print a test receipt.');await load();});});
$('paper').addEventListener('change',()=>{$('columns').value=$('paper').value==='58mm'?32:48;});
$('refresh').onclick=()=>action(()=>load());
$('test').onclick=()=>action(async()=>{await window.agent.test();message(state.preview?'Test queued in preview mode. No physical receipt will print.':'Test receipt queued. Check the printed result.');await load(false);});
$('cut-test').onclick=()=>action(async()=>{const sent=await window.agent.cut();if(sent)message(state.preview?'Cutter test simulated.':'Cutter command submitted. Check the printer.');});
$('copy').onclick=()=>action(async()=>{await window.agent.copyToken();message('Pairing token copied. Store it only on the authorized billing computer.');});
$('rotate').onclick=()=>{if(confirm('Disconnect paired browsers and generate a new token?'))action(async()=>{await window.agent.rotate();message('Pairing token reset. Copy the new token to reconnect Bilyqo.');});};
load().catch(e=>message(e.message,true));
setInterval(()=>{load(false).catch(()=>{});},3000);
